#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# Querying Nginx at its root (/) with a GET request (requesting a page)
# curl http://54.160.108.206/   --> returns string "Hello World!"
# curl http://54.160.108.206/   --> returns header info

apt-get update -y
apt-get install -y nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx restart
