#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# Querying Nginx at its root (/) with a GET request (requesting a page)
# curl http://54.160.108.206/   --> returns string "Hello World!"
# curl http://54.160.108.206/   --> returns header info

sudo apt-get update && sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index*.html
printf %s "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
            try_files \$uri \$uri/ =404;
        }
}
" | sudo tee /etc/nginx/sites-available/default
sudo service nginx reload
